### ISSUE TITLE
[Feature Request] worldwide numbers combined

### ISSUE THREAD

**Issue by chris400** [Niclaslach/vaccination-worker#1]
Plus provide an option to display the numbers of all countries in total.

**Comment by Niclaslach** [comment]
Feature Implemented. World is at the very bottom of the Country Selector (because I'm lazy 🤪). I'm not sure about the "Flag" on the jab. Blue? I only have 3x3 pixels... - Well it's white for now 😂

Commit: b0ea09a

**Comment by Niclaslach** [comment]
b0ea09aa957e7b96afacadf92cd4da7ccd637e52
